<a href="https://colab.research.google.com/github/Segn11/dataset-analysis-and-manipulation/blob/prediction/Tanzania_Tourism_prediction_dataset_analysis_and_manipulation_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Train (1).csv to Train (1).csv

In [2]:
import pandas as pd

# Use the exact filename shown after upload
df = pd.read_csv('Train (1).csv')

# Show the first few rows
df.head()

,ID,country,age_group,travel_with,total_female,total_male,purpose,main_activity,info_source,tour_arrangement,...,package_transport_tz,package_sightseeing,package_guided_tour,package_insurance,night_mainland,night_zanzibar,payment_mode,first_trip_tz,most_impressing,total_cost
0,tour_0,SWIZERLAND,45-64,Friends/Relatives,1.0,1.0,Leisure and Holidays,Wildlife tourism,"Friends, relatives",Independent,...,No,No,No,No,13.0,0.0,Cash,No,Friendly People,674602.5
1,tour_10,UNITED KINGDOM,25-44,NaN,1.0,0.0,Leisure and Holidays,Cultural tourism,others,Independent,...,No,No,No,No,14.0,7.0,Cash,Yes,"Wonderful Country, Landscape, Nature",3214906.5
2,tour_1000,UNITED KINGDOM,25-44,Alone,0.0,1.0,Visiting Friends and Relatives,Cultural tourism,"Friends, relatives",Independent,...,No,No,No,No,1.0,31.0,Cash,No,Excellent Experience,3315000.0
3,tour_1002,UNITED KINGDOM,25-44,Spouse,1.0,1.0,Leisure and Holidays,Wildlife tourism,"Travel, agent, tour operator",Package Tour,...,Yes,Yes,Yes,No,11.0,0.0,Cash,Yes,Friendly People,7790250.0
4,tour_1004,CHINA,1-24,NaN,1.0,0.0,Leisure and Holidays,Wildlife tourism,"Travel, agent, tour operator",Independent,...,No,No,No,No,7.0,4.0,Cash,Yes,No comments,1657500.0

In [3]:
age_series = df['age_group']

print(age_series.head())

0    45-64
1    25-44
2    25-44
3    25-44
4     1-24
Name: age_group, dtype: object

In [4]:
df[df['country'] == "USA"]

Empty DataFrame
Columns: [ID, country, age_group, travel_with, total_female, total_male, purpose, main_activity, info_source, tour_arrangement, package_transport_int, package_accomodation, package_food, package_transport_tz, package_sightseeing, package_guided_tour, package_insurance, night_mainland, night_zanzibar, payment_mode, first_trip_tz, most_impressing, total_cost]
Index: []

[0 rows x 23 columns]

In [5]:
df[df['country'] == "CHINA"]

,ID,country,age_group,travel_with,total_female,total_male,purpose,main_activity,info_source,tour_arrangement,...,package_transport_tz,package_sightseeing,package_guided_tour,package_insurance,night_mainland,night_zanzibar,payment_mode,first_trip_tz,most_impressing,total_cost
4,tour_1004,CHINA,1-24,NaN,1.0,0.0,Leisure and Holidays,Wildlife tourism,"Travel, agent, tour operator",Independent,...,No,No,No,No,7.0,4.0,Cash,Yes,No comments,1657500.0
38,tour_1046,CHINA,25-44,Alone,1.0,0.0,Leisure and Holidays,Beach tourism,"Newspaper, magazines,brochures",Independent,...,No,No,No,No,2.0,0.0,Other,No,Friendly People,828750.0
43,tour_1050,CHINA,1-24,Alone,0.0,1.0,Leisure and Holidays,Wildlife tourism,"Friends, relatives",Independent,...,No,No,No,No,34.0,4.0,Cash,Yes,Friendly People,3273562.5
124,tour_1150,CHINA,1-24,NaN,0.0,1.0,Visiting Friends and Relatives,Beach tourism,"Friends, relatives",Independent,...,No,No,No,No,24.0,3.0,Cash,Yes,Friendly People,2486250.0
196,tour_1238,CHINA,25-44,Friends/Relatives,2.0,1.0,Business,Wildlife tourism,"Travel, agent, tour operator",Independent,...,No,No,No,No,5.0,2.0,Cash,No,No comments,3315000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4578,tour_719,CHINA,25-44,Friends/Relatives,3.0,1.0,Leisure and Holidays,Wildlife tourism,"Travel, agent, tour operator",Independent,...,No,No,No,No,3.0,0.0,Cash,Yes,No comments,165750.0
4594,tour_738,CHINA,25-44,Friends/Relatives,2.0,0.0,Leisure and Holidays,Beach tourism,"Travel, agent, tour operator",Independent,...,No,No,No,No,5.0,4.0,Cash,No,Friendly People,16575000.0
4678,tour_833,CHINA,45-64,Friends/Relatives,1.0,5.0,Leisure and Holidays,Wildlife tourism,"Travel, agent, tour operator",Package Tour,...,No,No,No,No,10.0,0.0,Cash,Yes,No comments,8619000.0
4726,tour_895,CHINA,25-44,Friends/Relatives,1.0,1.0,Leisure and Holidays,Wildlife tourism,"Travel, agent, tour operator",Package Tour,...,Yes,Yes,Yes,No,10.0,5.0,Cash,Yes,No comments,8287500.0
4779,tour_961,CHINA,1-24,Friends/Relatives,0.0,2.0,Leisure and Holidays,Wildlife tourism,"Travel, agent, tour operator",Independent,...,No,No,No,No,10.0,5.0,Cash,Yes,Excellent Experience,281775.0

In [6]:
df.sort_values(by= 'age_group', ascending=True)

,ID,country,age_group,travel_with,total_female,total_male,purpose,main_activity,info_source,tour_arrangement,...,package_transport_tz,package_sightseeing,package_guided_tour,package_insurance,night_mainland,night_zanzibar,payment_mode,first_trip_tz,most_impressing,total_cost
1636,tour_3004,SOUTH AFRICA,1-24,Spouse,1.0,1.0,Leisure and Holidays,Beach tourism,"Travel, agent, tour operator",Package Tour,...,Yes,No,No,Yes,0.0,7.0,Cash,Yes,Friendly People,722517.0
681,tour_1837,UNITED STATES OF AMERICA,1-24,NaN,0.0,4.0,Leisure and Holidays,Conference tourism,"Radio, TV, Web",Package Tour,...,Yes,No,Yes,No,10.0,0.0,Cash,Yes,No comments,4309500.0
2728,tour_4323,UNITED KINGDOM,1-24,Alone,1.0,0.0,Leisure and Holidays,Conference tourism,"Travel, agent, tour operator",Package Tour,...,Yes,No,Yes,No,12.0,3.0,Cash,Yes,Wildlife,5304000.0
3939,tour_5785,ITALY,1-24,Spouse,1.0,1.0,Leisure and Holidays,Beach tourism,"Travel, agent, tour operator",Package Tour,...,Yes,No,No,No,0.0,7.0,Cash,Yes,No comments,6298500.0
1577,tour_2938,SWAZILAND,1-24,Friends/Relatives,1.0,1.0,Leisure and Holidays,Wildlife tourism,others,Independent,...,No,No,No,No,14.0,0.0,Cash,Yes,"Wonderful Country, Landscape, Nature",4889625.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,tour_2217,BELGIUM,65+,NaN,1.0,0.0,Leisure and Holidays,Bird watching,"Friends, relatives",Independent,...,No,No,No,No,11.0,0.0,Cash,No,Excellent Experience,4060875.0
595,tour_1732,AUSTRALIA,65+,Friends/Relatives,1.0,2.0,Leisure and Holidays,Wildlife tourism,"Travel, agent, tour operator",Package Tour,...,Yes,Yes,Yes,No,5.0,0.0,Credit Card,No,Wildlife,21547500.0
593,tour_1730,GERMANY,65+,Spouse,1.0,1.0,Leisure and Holidays,Wildlife tourism,"Travel, agent, tour operator",Package Tour,...,Yes,No,Yes,Yes,5.0,0.0,Cash,Yes,Wildlife,16906500.0
3155,tour_4815,UNITED STATES OF AMERICA,65+,Spouse,1.0,1.0,Leisure and Holidays,Wildlife tourism,"Travel, agent, tour operator",Package Tour,...,Yes,Yes,Yes,Yes,5.0,0.0,Credit Card,Yes,Wildlife,31943340.0
3114,tour_4772,UNITED STATES OF AMERICA,65+,Alone,1.0,0.0,Leisure and Holidays,Wildlife tourism,"Travel, agent, tour operator",Package Tour,...,Yes,Yes,Yes,No,4.0,0.0,Cash,Yes,Friendly People,1491750.0

In [7]:
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['ID', 'country', 'age_group', 'travel_with', 'total_female', 'total_male', 'purpose', 'main_activity', 'info_source', 'tour_arrangement', 'package_transport_int', 'package_accomodation', 'package_food', 'package_transport_tz', 'package_sightseeing', 'package_guided_tour', 'package_insurance', 'night_mainland', 'night_zanzibar', 'payment_mode', 'first_trip_tz', 'most_impressing', 'total_cost']

In [8]:
df.set_index('main_activity', inplace=True)


df[['payment_mode', 'info_source']].head()

                 payment_mode                   info_source
main_activity
Wildlife tourism         Cash            Friends, relatives
Cultural tourism         Cash                        others
Cultural tourism         Cash            Friends, relatives
Wildlife tourism         Cash  Travel, agent, tour operator
Wildlife tourism         Cash  Travel, agent, tour operator

In [9]:
df[df['total_cost'] >= 20000].to_csv("cash_players.csv", index=False)

In [10]:
# Total tourists per country
df.groupby('main_activity').size()

# Average nights spent on mainland by age group
df.groupby('main_activity')['total_cost'].mean()

main_activity
Beach tourism               7.524837e+06
Bird watching               4.216563e+06
Conference tourism          1.030680e+07
Cultural tourism            3.991139e+06
Diving and Sport Fishing    1.709434e+07
Hunting tourism             1.911327e+06
Mountain climbing           1.862857e+06
Wildlife tourism            1.059533e+07
business                    8.125078e+06
Name: total_cost, dtype: float64

In [11]:
df['total_nights'] = df['night_mainland'] + df['night_zanzibar']
print(df['total_nights'])

main_activity
Wildlife tourism    13.0
Cultural tourism    21.0
Cultural tourism    32.0
Wildlife tourism    11.0
Wildlife tourism    11.0
                    ...
Hunting tourism      2.0
Wildlife tourism    11.0
Wildlife tourism    10.0
Beach tourism        5.0
Wildlife tourism    11.0
Name: total_nights, Length: 4809, dtype: float64

In [12]:
# Travelers with guided tour and from SWITZERLAND
df[(df['package_guided_tour'] == 'Yes') & (df['payment_mode'] == 'Cash')]

,ID,country,age_group,travel_with,total_female,total_male,purpose,info_source,tour_arrangement,package_transport_int,...,package_sightseeing,package_guided_tour,package_insurance,night_mainland,night_zanzibar,payment_mode,first_trip_tz,most_impressing,total_cost,total_nights
main_activity,,,,,,,,,,,,,,,,,,,,,
Wildlife tourism,tour_1002,UNITED KINGDOM,25-44,Spouse,1.0,1.0,Leisure and Holidays,"Travel, agent, tour operator",Package Tour,No,...,Yes,Yes,No,11.0,0.0,Cash,Yes,Friendly People,7790250.0,11.0
Wildlife tourism,tour_1005,UNITED KINGDOM,25-44,NaN,0.0,1.0,Leisure and Holidays,"Travel, agent, tour operator",Package Tour,No,...,Yes,Yes,No,9.0,3.0,Cash,Yes,Wildlife,120950.0,12.0
Wildlife tourism,tour_1008,UNITED STATES OF AMERICA,45-64,Friends/Relatives,1.0,1.0,Leisure and Holidays,"Travel, agent, tour operator",Package Tour,Yes,...,Yes,Yes,Yes,10.0,3.0,Cash,Yes,Friendly People,3480750.0,13.0
Wildlife tourism,tour_1035,SPAIN,45-64,Spouse and Children,3.0,1.0,Leisure and Holidays,"Travel, agent, tour operator",Package Tour,Yes,...,Yes,Yes,Yes,4.0,4.0,Cash,Yes,Wildlife,25442625.0,8.0
Conference tourism,tour_1036,FRANCE,1-24,NaN,0.0,1.0,Leisure and Holidays,others,Package Tour,No,...,Yes,Yes,Yes,11.0,3.0,Cash,Yes,"Wonderful Country, Landscape, Nature",6961500.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wildlife tourism,tour_981,SWIZERLAND,45-64,Spouse,1.0,1.0,Leisure and Holidays,"Travel, agent, tour operator",Package Tour,Yes,...,Yes,Yes,No,10.0,5.0,Cash,Yes,Wildlife,38339920.0,15.0
Wildlife tourism,tour_986,UNITED STATES OF AMERICA,65+,Alone,1.0,0.0,Leisure and Holidays,"Travel, agent, tour operator",Package Tour,Yes,...,Yes,Yes,Yes,19.0,0.0,Cash,Yes,Wildlife,18232500.0,19.0
Conference tourism,tour_987,SINGAPORE,1-24,Friends/Relatives,1.0,1.0,Leisure and Holidays,"Friends, relatives",Package Tour,Yes,...,No,Yes,No,14.0,2.0,Cash,Yes,Good service,9945000.0,16.0
Wildlife tourism,tour_994,UNITED STATES OF AMERICA,25-44,Spouse,1.0,1.0,Leisure and Holidays,"Travel, agent, tour operator",Package Tour,Yes,...,Yes,Yes,Yes,11.0,0.0,Cash,Yes,Friendly People,10690875.0,11.0
Wildlife tourism,tour_999,UNITED KINGDOM,25-44,Spouse,1.0,1.0,Leisure and Holidays,"Travel, agent, tour operator",Package Tour,Yes,...,Yes,Yes,No,4.0,7.0,Cash,Yes,Friendly People,13260000.0,11.0

In [13]:
# df.sort_values(by='total_nights', ascending=False)
df.sort_values(by='main_activity')

,ID,country,age_group,travel_with,total_female,total_male,purpose,info_source,tour_arrangement,package_transport_int,...,package_sightseeing,package_guided_tour,package_insurance,night_mainland,night_zanzibar,payment_mode,first_trip_tz,most_impressing,total_cost,total_nights
main_activity,,,,,,,,,,,,,,,,,,,,,
Beach tourism,tour_5766,ZIMBABWE,25-44,Friends/Relatives,0.0,2.0,Business,"Friends, relatives",Independent,No,...,No,No,No,2.0,0.0,Cash,Yes,Wildlife,828750.0,2.0
Beach tourism,tour_3508,KENYA,25-44,Children,1.0,1.0,Visiting Friends and Relatives,"Friends, relatives",Independent,No,...,No,No,No,0.0,14.0,Cash,No,Friendly People,497250.0,14.0
Beach tourism,tour_3501,UNITED STATES OF AMERICA,25-44,Spouse,1.0,1.0,Leisure and Holidays,"Travel, agent, tour operator",Package Tour,Yes,...,No,No,No,0.0,4.0,Cash,Yes,No comments,11701950.0,4.0
Beach tourism,tour_3491,ZIMBABWE,1-24,Friends/Relatives,0.0,2.0,Business,"Friends, relatives",Independent,No,...,No,No,No,5.0,0.0,Cash,No,"Wonderful Country, Landscape, Nature",1910000.0,5.0
Beach tourism,tour_3490,ITALY,25-44,Spouse,1.0,1.0,Leisure and Holidays,"Friends, relatives",Package Tour,Yes,...,Yes,Yes,Yes,0.0,7.0,Cash,Yes,No comments,6696300.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
business,tour_5998,INDIA,45-64,NaN,0.0,1.0,Visiting Friends and Relatives,"Friends, relatives",Independent,No,...,No,No,No,70.0,0.0,Cash,No,No comments,1004000.0,70.0
business,tour_5706,ITALY,25-44,Spouse,1.0,1.0,Leisure and Holidays,"Travel, agent, tour operator",Package Tour,Yes,...,No,Yes,No,0.0,7.0,Cash,Yes,No comments,7942655.0,7.0
business,tour_5049,SOUTH AFRICA,25-44,Spouse,1.0,1.0,Leisure and Holidays,"Travel, agent, tour operator",Package Tour,Yes,...,No,No,No,0.0,7.0,Credit Card,Yes,Friendly People,55360500.0,7.0
business,tour_2583,NETHERLANDS,25-44,NaN,0.0,1.0,Leisure and Holidays,"Friends, relatives",Independent,No,...,No,No,No,0.0,5.0,Cash,Yes,Friendly People,497250.0,5.0
business,tour_5855,UNITED KINGDOM,25-44,Alone,0.0,1.0,Leisure and Holidays,"Newspaper, magazines,brochures",Package Tour,Yes,...,Yes,Yes,Yes,5.0,4.0,Cash,Yes,No comments,7790250.0,9.0

In [14]:
df.describe(include='all')  # includes both numeric and categorical data

,ID,country,age_group,travel_with,total_female,total_male,purpose,info_source,tour_arrangement,package_transport_int,...,package_sightseeing,package_guided_tour,package_insurance,night_mainland,night_zanzibar,payment_mode,first_trip_tz,most_impressing,total_cost,total_nights
count,4809,4809,4809,3695,4806.000000,4804.000000,4809,4809,4809,4809,...,4809,4809,4809,4809.000000,4809.000000,4809,4809,4496,4.809000e+03,4809.000000
unique,4809,105,4,5,NaN,NaN,7,8,2,2,...,2,2,2,NaN,NaN,4,2,7,NaN,NaN
top,tour_999,UNITED STATES OF AMERICA,25-44,Alone,NaN,NaN,Leisure and Holidays,"Travel, agent, tour operator",Independent,No,...,No,No,No,NaN,NaN,Cash,Yes,Friendly People,NaN,NaN
freq,1,695,2487,1265,NaN,NaN,2840,1913,2570,3357,...,3319,3259,4079,NaN,NaN,4172,3243,1541,NaN,NaN
mean,NaN,NaN,NaN,NaN,0.926758,1.009575,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.488043,2.304429,NaN,NaN,NaN,8.114389e+06,10.792472
std,NaN,NaN,NaN,NaN,1.288242,1.138865,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.427624,4.227080,NaN,NaN,NaN,1.222490e+07,10.779025
min,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,4.900000e+04,0.000000
25%,NaN,NaN,NaN,NaN,0.000000,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.000000,0.000000,NaN,NaN,NaN,8.121750e+05,4.000000
50%,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6.000000,0.000000,NaN,NaN,NaN,3.397875e+06,8.000000
75%,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,11.000000,4.000000,NaN,NaN,NaN,9.945000e+06,14.000000
max,NaN,NaN,NaN,NaN,49.000000,44.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,145.000000,61.000000,NaN,NaN,NaN,9.953288e+07,145.000000

In [15]:
df[['night_mainland', 'night_zanzibar']].mean()

night_mainland    8.488043
night_zanzibar    2.304429
dtype: float64

In [28]:
df['total_male'] = df['total_male'].fillna(0)

In [29]:
# Strip whitespace in string columns
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

In [30]:
# Convert numeric-like columns
numeric_cols = [ 'total_male', 'night_mainland', 'night_zanzibar', 'total_cost']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [31]:
# Feature engineering
# df['total_people'] = df['total_female'] + df['total_male']
df['total_nights'] = df['night_mainland'] + df['night_zanzibar']
# df['cost_per_person'] = df['total_cost'] / df['total_people']
df['cost_per_night'] = df['total_cost'] / df['total_nights']